FROM node:16-alpine

WORKDIR /app

# Копируем файлы зависимостей
COPY frontend/package.json frontend/package-lock.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем исходный код
COPY frontend/ .

# Устанавливаем переменные окружения для продакшена
ARG API_URL
ENV NEXT_PUBLIC_API_URL=${API_URL}

# Собираем приложение
RUN npm run build

# Экспонируем порт
EXPOSE 3000

# Запускаем приложение
CMD ["npm", "start"] 